# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('temp_today', models.IntegerField()),
                ('temp_tomorrow', models.IntegerField()),
            ],
        ),
    ]
