# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='alert_temp',
            field=models.IntegerField(default=15),
        ),
    ]
